baseurl = "/"
builddrafts = false
canonifyurls = false
languageCode = "en-us"
title = "Leo's website"
theme = "hugo-initio"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    name = "Leo Ramirez-Lopez"
    email = "ramirez.lopez.leo@gmail.com"
    phone = ""
    address = "St Gallen, Switzerland"
    year = 2020
    avatar = "images/leo-ramirez-lopez.jpg"
    avatarclass = "circle"
    background = ""
    banner = "images/bg_head.jpg"
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownload = true
    showClients = false

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = true
    footerEnableFormWidget = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5

[[params.social]]
	title = "twitter"
	url = "https://twitter.com/rlleonardo"
    icon = "fab fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/leo-ramirez-lopez"
    icon = "fab fa-linkedin"
    footer = false
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "github"
	url = "https://github.com/l-ramirez-lopez"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:leo.ramirez.lopez@gmail.com"
    icon = "fas fa-envelope-square"
    footer = false
    sharethis = true
    network = "email"
